min_conf:
  type: uniform
  default: 0.1  # from the default parameters
  range: [0.1, 0.3]

track_thresh:
  type: uniform
  default: 0.6  # from the default parameters
  range: [0.4, 0.7]

track_buffer:
  type: qrandint
  default: 30  # from the default parameters
  range: [10, 61, 10]  # step size of 10, upper bound exclusive

match_thresh:
  type: uniform
  default: 0.9  # from the default parameters
  range: [0.7, 0.9]

frame_rate:
  type: choice
  default: 30  # from the default parameters
  options: [25, 30]  # static choice for Ray Search

std_weight_position:
  type: choice
  default: 0.05
  options: [0.05]

std_weight_velocity:
  type: choice
  default: 0.00625
  options: [0.00625]
